### ISSUE TITLE
post to Twitter failure with error Unauthorized

### ISSUE THREAD

**Issue by hungdm9999** [socioboard/Socioboard-Core-3.0#14]
Hi everyone,
I'm testing twitter channel with Socioboard latest release (3.0.11), almost works fine (register account, login, add twitter credentials, Schedule new post..).
Running SocioboardDataScheuler with option 2 (Twitter), i always received error 401, Unauthorized as shown in attached picture.

Is any work around on this issue please?

Thank you,
Hung
<img width="598" alt="screen shot 2017-05-03 at 11 30 09 am" src="https://cloud.githubusercontent.com/assets/3163895/25648229/f4be478a-2ff3-11e7-95bf-7efd7af94397.png">

**Comment by socioboard** [comment]
Hi hungdm9999,
I think you have some access token issue,can you just remove your account and add once again.then it'll may work.

**Comment by hungdm9999** [comment]
Thanks,
i looked at table twitteraccounts, access-token and access-token-secret look good.  I also make a clean & cleared database even several times (mysql, mongo and redis are all flushed). It is still not working.
Do you think it is some thing wrong with timestamp?

**Comment by socioboard** [comment]
Have you deleted your twitter account from database?
1. delete from twitteraccount table..
2.delete from groupprofiles
then add again.

**Comment by socioboard** [comment]
We uploaded a new code.please take latest updated code.

**Comment by hungdm9999** [comment]
Hi,
I did,
1. Truncate 3 tables: groupprofiles, twitteraccount, shedulemessage
2. Flush all on Redis (i.e: delete all key-value pairs)
3. Remove All Documents from Mongo
4. Add new twitter profile and Schedule new post.
5. All  done as expected, mysql have desired information.
6. Start scheduler to post then i still received 401 (Unauthorized). I think twitter  change their procedure, detail here: https://dev.twitter.com/rest/reference/post/statuses/update_with_media,
then endpoint socioboard is referring is https://api.twitter.com/1.1/statuses/update_with_media.json is deprecated.
Should we look deeper in here?

Thank you,

**Comment by socioboard** [comment]
Please run updated code for data scheduler and also make sure to change appsetting.
SS- http://prntscr.com/f3kjwd
use your own app consumerkey and secretkey...

**Comment by hungdm9999** [comment]
Hi,
i configured with my own credentials at beginning of this thread. All params were put on AppSetting (ss1), not hard-code directly into the multiple location (as ss2).

I still have 401 with latest source (clone from master branch).

**Comment by socioboard** [comment]
can i have your team viewer access?so i can check what is the issue.

**Comment by hungdm9999** [comment]
i think it is great, where can i send you teamview login id/pass? I'm using latest teamviewer version.

**Comment by socioboard** [comment]
You can send me here...

**Comment by hungdm9999** [comment]
id/pass: 287 773 821/8y53wa

**Comment by socioboard** [comment]
when should i connect?tell me some exact time when you available online?

**Comment by hungdm9999** [comment]
you can access now with 287 773 821/c175ji, please

**Comment by socioboard** [comment]
Will access at 10:45...after 25 minutes from now.

**Comment by hungdm9999** [comment]
ok, see you at 10.45, New Delhi time, thanks

**Comment by hungdm9999** [comment]
here is the id: 287 773 821/pe391k

**Comment by socioboard** [comment]
check your password again previous one is not working

**Comment by hungdm9999** [comment]
547utx

**Comment by hungdm9999** [comment]
Hi, 
Thanks for your support, the problem was my mistake and twitter as well. A potential issue from twitter is that Tw will still grant oauth credentials without any app created. This leads to my certain that the app is still there actually but it is not.
The problem is solved and once again thank for your agressive support.
