### ISSUE TITLE
Schedule new Twitter message failure

### ISSUE THREAD

**Issue by hungdm9999** [socioboard/Socioboard-Core-3.0#15]
Hi dev team,
Adding a new post to twitter, i got a pop show success result but nothing in socio queue.
Having a look deeper, exception thrown with null of <code>localscheduletime</code>, please have it fixed in SocioMessagesController.cs so others can avoid it.

Thank you very much,
Hung,

**Comment by socioboard** [comment]
You need to add localscheduletime column in scheduledmessage table.datatype for this is DATETIME.

**Comment by hungdm9999** [comment]
Hello,
exception thrown when you try to parse <code>localscheduletime</code> which is <code>null</code> from String to DateTime.
It is before insertion.
PS: latest schema already have field <code> localscheduletime</code> , your previous suggestion is not required to execute.
Thanks,

**Comment by socioboard** [comment]
Have you deleted your twitter account from database?
1. delete from twitteraccount table..
2.delete from groupprofiles
then add again.

**Comment by socioboard** [comment]
Can you tell me where you exactly get this exception.please send me screenshot for this exception.

**Comment by hungdm9999** [comment]
Hi,
SocialMessagesController invoke **ScheduleMessageHelper.ScheduleMessage** to process post.

The line: userlocalscheduletime=DateTime.Parse(localschduletime) raises Exception.
I temporarily by pass this error by some tricks in attached file.

Thanks

<img width="1175" alt="screen shot 2017-05-03 at 3 16 00 pm" src="https://cloud.githubusercontent.com/assets/3163895/25652677/9b883dea-3013-11e7-8fa2-bfa844cd08ea.png">

**Comment by socioboard** [comment]
We uploaded a new code.please take latest updated code.

**Comment by hungdm9999** [comment]
(y), thanks for your work,

**Comment by socioboard** [comment]
Thanks closing this issue now :)
