### ISSUE TITLE
Socio Queue listing error

### ISSUE THREAD

**Issue by hungdm9999** [socioboard/Socioboard-Core-3.0#16]
Hi,
the master-branch have issues with SocioQueue as below:
The SocioQueue listing functions is working incorrectly.
1. It not display all scheduled message. I.e: if you have 2 posts in mysql and 1 cached in redis, it will only looks at Redis and display one.
2. Message was sent is not removed on Redis.
3. The above issue leads to second, post was sent (tweeted to Tw), status=1(sent), but still display as <code>Pending</code>

Hope they will be resolved soon,
Thanks,

**Comment by socioboard** [comment]
Hi hungdm9999,
sorry for late reply 
Take the new updates of socioboard 3.0 and check if you face same
issue please let us know 

Thanks
SB Technical Team
