### ISSUE TITLE
How to delete a Facebook Fanpage Analityc?

### ISSUE THREAD

**Issue by pablojastorga** [socioboard/Socioboard-Core-3.0#19]
Hi, I can't find the way to delete a Facebook fanpage analytic. Now I'm trying to add the facebook page and  i get a popup who say "Page added by other user".  Any ideas?  thanks. 

Maybe this is not the right place for this issue, but I have sent a mail and I have no answer.  Thanks.

**Comment by socioboard** [comment]
Hi pablojastorga,
We will released new update for this feature.it will be replicate in next update.
