### ISSUE TITLE
can this compile in VS2017 ?

### ISSUE THREAD

**Issue by Zzzaps** [socioboard/Socioboard-Core-3.0#21]
Getting errors:
Severity	Code	Description	Project	Path	File	Line	Suppression State
Error	CS0246	The type or namespace name 'Newtonsoft' could not be found (are you missing a using directive or an assembly reference?)	GlobusLinkedinLib	C:\Zap\SocioBoard\SocioboardAPI\Library\GlobusLinkedinLib\App.Core	C:\Zap\SocioBoard\SocioboardAPI\Library\GlobusLinkedinLib\App.Core\LinkedinCompanyPage.cs	10	Active

Any hints on how to fix would be appreciated.

**Comment by socioboard** [comment]
Hi Zzzaps,
we are working on the same issue once done we will push new build on github.

Thanks
Socioboard Team

**Comment by Zzzaps** [comment]
No change with new build. Any suggestions?

**Comment by Zzzaps** [comment]
No change with new build. Any suggestions?

**Comment by socioboard** [comment]
Hi Zzzaps ,
Take new update of socioboard 3.0 and check .if you face same issue please let us know

Thanks
SB Technical Team
