### ISSUE TITLE
socioboard error message

### ISSUE THREAD

**Issue by tejamareddy** [socioboard/Socioboard-Core-3.0#26]
![socioboard j](https://user-images.githubusercontent.com/25472813/27370281-811f321a-5679-11e7-9788-abc9035d51d4.jpg)
Hi, I build the socioboard project successfully.But while running the project code i am unable to start the process in localhost.Please help me.

**Comment by socioboard** [comment]
Hi tejamareddy,
clean the solution and rebuild the project

**Comment by tejamareddy** [comment]
![socioboardruntimeerror](https://user-images.githubusercontent.com/25472813/27375938-4194f46c-568e-11e7-913c-cb4990a1bc89.jpg)
Hi, After cleaning the solution and rebuilded the project im getting these type of errors.Please help me.

**Comment by socioboard** [comment]
Hi tejamareddy,
which visual studio version are you using ?

**Comment by tejamareddy** [comment]
2017

**Comment by socioboard** [comment]
Do you have visual studio 2015 ?
if you have then try once if not then wait for sometime & let you 
know whether it supporting vs 2017 or not.

**Comment by tejamareddy** [comment]
No, i didn't have.
