### ISSUE TITLE
socioboard project loading issue in Visual Studio 2015

### ISSUE THREAD

**Issue by tejamareddy** [socioboard/Socioboard-Core-3.0#27]
Hi,
 When i am loading the socioboard sln file into my visual studio 2015 the project files that are in socioboard project is not loading.Can you give me the solution.

**Comment by tejamareddy** [comment]
![socioboard](https://user-images.githubusercontent.com/25472813/27572084-76e78330-5b27-11e7-8daa-03293c325ecc.jpg)
this is the issue im getting. Can you help me

**Comment by socioboard** [comment]
Hi tejamareddy,
Just updates notification given upper side .
and install asp.net core preview  .
![image](https://user-images.githubusercontent.com/6312383/27572835-f1fc7036-5b2b-11e7-90bd-e6b2fd87a90d.png)

**Comment by tejamareddy** [comment]
how can i install it

**Comment by socioboard** [comment]
For installation details please talk to our support team he will assist you .

Thanks
Socioboard Technical Team
