### ISSUE TITLE
errors occuring while building the socioboard project

### ISSUE THREAD

**Issue by tejamareddy** [socioboard/Socioboard-Core-3.0#28]
Severity Code Description Project File Line Suppression State
Error NU1001 The dependency System.Reflection.Primitives >= 4.0.1 could not be resolved. Api.Socioboard D:\Socioboard-Core-3.0-master\src\Api.Socioboard\project.json 3

**Comment by tejamareddy** [comment]
![socioboarderror](https://user-images.githubusercontent.com/25472813/27580916-c2feefe8-5b49-11e7-9761-dff16fca80f1.jpg)
please help me while building im facing these errors.

**Comment by tejamareddy** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0433	The type 'HttpUtility' exists in both 'Hammock.ClientProfile, Version=1.0.0.0, Culture=neutral, PublicKeyToken=c148cfba29ed1a4d' and 'Hammock, Version=1.0.0.0, Culture=neutral, PublicKeyToken=c148cfba29ed1a4d'	Socioboard.Instagram	D:\Socioboard-Core-3.0-master\src\Socioboard.Instagram\Authentication\oAuthBase.cs	335	
Error	CS0433	The type 'HttpUtility' exists in both 'Hammock.ClientProfile, Version=1.0.0.0, Culture=neutral, PublicKeyToken=c148cfba29ed1a4d' and 'Hammock, Version=1.0.0.0, Culture=neutral, PublicKeyToken=c148cfba29ed1a4d'	Api.Socioboard	D:\Socioboard-Core-3.0-master\src\Api.Socioboard\Repositories\ListeningRepository\FacebookGroupPostRepository.cs	43	
Error	CS0433	The type 'HttpUtility' exists in both 'Hammock.ClientProfile, Version=1.0.0.0, Culture=neutral, PublicKeyToken=c148cfba29ed1a4d' and 'Hammock, Version=1.0.0.0, Culture=neutral, PublicKeyToken=c148cfba29ed1a4d'	Api.Socioboard	D:\Socioboard-Core-3.0-master\src\Api.Socioboard\Repositories\ListeningRepository\LinkedInGroupPostRepository.cs	56	
Error	NU1002	The dependency BundlerMinifier.Core 2.3.327 does not support framework .NETFramework,Version=v4.5.1.	Socioboard	D:\Socioboard-Core-3.0-master\src\Socioboard\project.json	32	
I solved errors mostly.I am unable to solve these errors.Could you please help me and give me the solution.

**Comment by socioboard** [comment]
Hi Tejamareddy,
we are checking now when we finish it will let you know about the solution.

Thanks
SB Technical Team

**Comment by tejamareddy** [comment]
ok thanks

**Comment by tejamareddy** [comment]
![socioboarddebug](https://user-images.githubusercontent.com/25472813/27625435-40ae98e0-5c02-11e7-86f2-4b1c5f1b512a.jpg)
I have unloaded the project and reloaded  and followed the procedure step by step  i didnt  get any errors but when im starting debugging im getting this issue.
