### ISSUE TITLE
registration page error

### ISSUE THREAD

**Issue by tejamareddy** [socioboard/Socioboard-Core-3.0#29]
![registration error](https://user-images.githubusercontent.com/25472813/27673701-f56deaac-5c56-11e7-8fc9-0110c8990e3f.jpg)
while registering the account details in localhost  my details has to be stored in database right. And i need to get login page.But here while registering account the data is not storing and it is stucked in this page only. Can you give me the solution.

**Comment by socioboard** [comment]
Hi tejamareddy,
Just debug the code and check what is the error because we don't know your setting 
so go through our document and check thoroughly.
Thanks
SB Technical Team
