### ISSUE TITLE
Unable to start process E:Socioboard-core-3.0-master\Socioboard-Core-3.0-master\src\Socioboard\bit\debug\net451\win7-x86\Socioboard.exe

### ISSUE THREAD

**Issue by maksudcs** [socioboard/Socioboard-Core-3.0#3]
> Unable to start process E:Socioboard-core-3.0-master\Socioboard-Core-3.0-master\src\Socioboard\bit\debug\net451\win7-x86\Socioboard.exe. the web server request failed with status code500, internal server error. The full response hase been written to 
> C:\Users\PCName\AppData\Local\Temp\HttpFailure_04-58-22.html
> ![untitled](https://cloud.githubusercontent.com/assets/17357327/22396247/706c6396-e57e-11e6-9983-e76289ddadd3.png)
>

**Comment by socioboard** [comment]
Hi maksudcs,
just clean the project (right click on project and select the option clean solution),
rebuild it again and run it .

Thanks
socioboard team

**Comment by maksudcs** [comment]
thanks for reply.

Clean or rebuild does not work. 
simply clean the temp folder = > restart the PC  => again rebuild the solution then worked perfectly.
