### ISSUE TITLE
when add facebook profie and page,have a mistake is invalid access token

### ISSUE THREAD

**Issue by hucoco123** [socioboard/Socioboard-Core-3.0#30]
We are a company from China, is trying to your company's products, its more in-depth development. We will integrate more social platforms in the future.
we like it very much
When I add a facebook account, there will be a mistake，pls see the picture
Will facebook the process of setting up the process need to pay attention to what the problem?
Facebook developer page seems to set exactly the correct, socioboard configuration file is also set correctly, ask what is the failure of the problem?
![i1 cimgpsh_orig](https://user-images.githubusercontent.com/29770990/27677232-7d8cb4a4-5ce3-11e7-9fa6-3dd198f79cc9.png)

**Comment by socioboard** [comment]
Hi hucoco123,
This token verified from facebook side so check your account first or give the socioboard account so that 
our team will track the actual issue .

Thanks
SB Technical Team

**Comment by hucoco123** [comment]
hi:
   thank you very much.
   I have develop it on my sever.
   my facebook develpoper account is 8615129006200  secret is ay86306010.
   the facebook app is :7billion
thanks
coco

**Comment by socioboard** [comment]
Hi Hucoco123 ,
Good to hear that you have solve the problem.
I am closing the issue .In future if you face any problem regarding socioboard product
just let us know.

Thanks
Socioboard Technical Team

**Comment by hucoco123** [comment]
hi：
   It didn't solve.
   I mean I have develop it on my sever,but it has a mistake that add facebook invalid access token
