### ISSUE TITLE
Missing required parameter: client_id

### ISSUE THREAD

**Issue by tejamareddy** [socioboard/Socioboard-Core-3.0#31]
![parameter](https://user-images.githubusercontent.com/25472813/27852586-9c0356ec-6114-11e7-8fb1-9f1d205f1480.jpg)
while adding our social profiles in socioboard we have to get  Grant access to our profile to share updates and view our feed information.but while adding our social profiles it is not giving access and it is showing missing required parameter:client_id . can you give me the solution.

**Comment by socioboard** [comment]
Hi ,
 Do you have  key and credential for google account.

**Comment by tejamareddy** [comment]
i added but im facing issue. Can you help me

**Comment by socioboard** [comment]
What issue you are facing give us detail.

**Comment by tejamareddy** [comment]
In the app setting i have created api keys for google 
![appsettings](https://user-images.githubusercontent.com/25472813/27864423-5bf4e532-6143-11e7-9b60-50d8cded9ad2.jpg
while running my project in local server we have toadd our social profiles in socioboard we have to get Grant access to our profile to share updates and view our feed information.but while adding our social profiles it is not giving access and it is showing missing required parameter:client_id . can you give me the solution.

**Comment by socioboard** [comment]
for that you need take permission from facebook .just check the facebook developer site they have explain already there how to use facebook api for web application.go through the document and apply the concept.give proper key and credential

**Comment by tejamareddy** [comment]
ok
