### ISSUE TITLE
FatalExecutionEngineError occurred

### ISSUE THREAD

**Issue by mabualwafa** [socioboard/Socioboard-Core-3.0#34]
when trying to login by email and password, the below exception appears, 

Managed Debugging Assistant 'FatalExecutionEngineError' has detected a problem in 'D:\Security\Socioboard\Socioboard-Core-3.0-master\src\Socioboard\bin\Debug\net451\win7-x64\Socioboard.exe'.

Additional information: The runtime has encountered a fatal error. The address of the error was at 0x4e73f23f, on thread 0x4c18. The error code is 0xc0000005. This error may be a bug in the CLR or in the unsafe or non-verifiable portions of user code. Common sources of this bug include user marshaling errors for COM-interop or PInvoke, which may corrupt the stack.

please advise me.

![2017-07-19_23-43-55](https://user-images.githubusercontent.com/20492882/28388795-85deb39c-6cdc-11e7-8e0c-751e35bb0fff.jpg)

**Comment by socioboard** [comment]
Hi mabualwafa,
upload new updated version of socioboard 3.0
