### ISSUE TITLE
how can use sqlserver database

### ISSUE THREAD

**Issue by aghili371** [socioboard/Socioboard-Core-3.0#36]
i wana using sqlserver database.
how can i config project and create sqlserver datbase?

**Comment by socioboard** [comment]
Hi aghili371
use nhibernate , change the connection string

**Comment by aghili371** [comment]
thank you .but i need sqlserver  database script. this script just for mysql database.

**Comment by socioboard** [comment]
Hi aghili371,
 for sqlserver script you have to google it, because we are using mysql script .

Thanks
Socioboard Team
