### ISSUE TITLE
error : Message = "No persister for: Domain.Socioboard.Models.User"

### ISSUE THREAD

**Issue by aghili371** [socioboard/Socioboard-Core-3.0#37]
hi
when i  want to register new user i get this error
Message = "No persister for: Domain.Socioboard.Models.User"
![1](https://user-images.githubusercontent.com/24512878/29138196-238516fa-7d58-11e7-9780-74f77d37eb95.jpg)
![2](https://user-images.githubusercontent.com/24512878/29138195-23800c14-7d58-11e7-90fd-658e5f5d1be4.jpg)

i using vs.net 2017and i set mysql  database and i changed conection string config.

**Comment by socioboard** [comment]
go inisde see what exactly cuase of this 
error detail given give the screen shot of it
![image](https://user-images.githubusercontent.com/6312383/29260718-2780b130-80e9-11e7-9bd4-64e01ca15d96.png)

**Comment by aghili371** [comment]
thank you
![1](https://user-images.githubusercontent.com/24512878/29477446-ba35a1ce-847d-11e7-93af-717f6d233199.jpg)
![2](https://user-images.githubusercontent.com/24512878/29477447-ba38389e-847d-11e7-8bf6-7a6ba4754a00.jpg)
![3](https://user-images.githubusercontent.com/24512878/29477448-ba3b0e48-847d-11e7-8898-029e30eed5cf.jpg)

**Comment by socioboard** [comment]
Hi aghili371,
its difficult to find the real bug so our technical team wants to take remote access of ur system 
for checking the issue if you don't mind .please provide ur skype id to our socioboard support team .
Thanks 
Socioboard Team

**Comment by socioboard** [comment]
Hi aghili371,
Have you got solution for the query you asked?
if not please let us know .

Thanks
Socioboard Team

**Comment by karelit0** [comment]
hi every one, I have the same problem, if you know the solution please help me.

**Comment by karelit0** [comment]
Solution is: include from the project "Domain.Socioboard" all the NHibernate maps on the folder "compiler/resources/Mappings" as embebed resources
