### ISSUE TITLE
.xproj Error

### ISSUE THREAD

**Issue by RajibBiswas** [socioboard/Socioboard-Core-3.0#39]
Hi, I am having issues while running the .sln with Visual Studio 2015. Error says -
.... error  : The imported project "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  Socioboard-Core-3.0-master\src\Api.Socioboard\Api.Socioboard.xproj

**Comment by socioboard** [comment]
Hi RajibBiswas
just clean the project and build the program , run again .

Thanks

**Comment by RajibBiswas** [comment]
Sorry but may be i am missing something. i am still having the same. No cleaning option is available as no projects are loaded -
![untitled](https://user-images.githubusercontent.com/10402594/29777237-15638dca-8c2d-11e7-8396-1b3217f68eeb.png)

**Comment by socioboard** [comment]
Hi RajibBiswas,
![image](https://user-images.githubusercontent.com/6312383/29777422-95d82c62-8c29-11e7-99ae-0dc676ec5916.png)
update this also.

**Comment by RajibBiswas** [comment]
Thanks for your help, its workig now, my bad, this issue was disscussed https://github.com/dotnet/core/issues/271. Fixing the installation of dotnet core made it word. Thank you again for your help, response and guide.
