### ISSUE TITLE
Can't Create User

### ISSUE THREAD

**Issue by deepakkumarvaishnav91** [socioboard/Socioboard-Core-3.0#40]
i am done with the installation process. But when i try to register with "basic(free plan)" . it shows me an error "Can't create user".
i m new in business. I am running a startup and i want to grow my business using social media network.. please reply as soon as possible as i am stuck with this problem for 2 days.

**Comment by socioboard** [comment]
Hi deepakkumarvaishnav91,
you using socioboard mobile app or web app . just do one thing send the mail to support team
i.e  sumit@socioboard.com or you can clerify your doubt using skype ,Our skype id:  (socioboard.support)

**Comment by deepakkumarvaishnav91** [comment]
I am using it on local host.
I have installed the socioboard on my local server using the instructions
given on github..

**Comment by socioboard** [comment]
can you provide your id for remote access so that we can find exact issue you facing.

**Comment by deepakkumarvaishnav91** [comment]
right now i m using it on local host.. i can provide you the screen shot

**Comment by socioboard** [comment]
OK sure

**Comment by deepakkumarvaishnav91** [comment]
i have attached the screen shot

**Comment by socioboard** [comment]
if you really wanna solve the problem just ask support team, we have given the id earlier  add them and chat

**Comment by shambhuadvanz101** [comment]
I am having the same issue ? Could you please let me know what solution have you done ?

Regard
