### ISSUE TITLE
Admin User

### ISSUE THREAD

**Issue by doveraudio** [socioboard/Socioboard-Core-3.0#41]
May I have specific instructions on creating Admin User please?
Regards,
Jeremy Leach

**Comment by GKG4** [comment]
I am also looking for the same.
Moreover, my Facebook Login is not working as well, getting error Facebook Not returning email.
Can you help?

**Comment by socioboard** [comment]
Hi Guys,
for admin just make a entry in user table and type should be 'SuperAdmin'.

Thanks 
SB Team

**Comment by socioboard** [comment]
Hi guys,
i hope you have found the solution so am closing this issue

Thanks
SB team
