### ISSUE TITLE
Facebook Not returning email

### ISSUE THREAD

**Issue by GKG4** [socioboard/Socioboard-Core-3.0#42]
Whenever I am trying to login with the Facebook App, I am getting error Facebook Not returning email.
What needs to be done in order to fix it?

Also, how to login as Admin into the website, or add users manually?
There is documentation available for details I guess.

**Comment by socioboard** [comment]
Hi GKG4,
login with facebook again , but before login check 'facebook account' should not block. 
if still problem persist check with our support team for help.
for document :  we are updating it ,when it done will upload soon in live

Thanks 
SB Team

**Comment by socioboard** [comment]
Hi GKG4,
i hope you have found the solution for it if not please let us know
for now am closing the issue

Thanks
SB team
