### ISSUE TITLE
No persister for: Domain.Socioboard.Models.User

### ISSUE THREAD

**Issue by meysam-d** [socioboard/Socioboard-Core-3.0#43]
hi
when I want register user in  Socioboard I see this Exception.
please help me.

"	ex	{"No persister for: Domain.Socioboard.Models.User"}	System.Exception {NHibernate.MappingException}"

**Comment by socioboard** [comment]
Hi meysam ,
can you please show us screen shot of the error.

Thanks
SB team

**Comment by meysam-d** [comment]
hi

"_### at NHibernate.Impl.SessionFactoryImpl.GetEntityPersister(String entityName) at NHibernate.Impl.SessionImpl.GetEntityPersister(String entityName, Object obj) at NHibernate.Event.Default.AbstractSaveEventListener.SaveWithGeneratedId(Object entity, String entityName, Object anything, IEventSource source, Boolean requiresImmediateIdAccess) at NHibernate.Event.Default.DefaultSaveOrUpdateEventListener.SaveWithGeneratedOrRequestedId(SaveOrUpdateEvent event) at NHibernate.Event.Default.DefaultSaveOrUpdateEventListener.EntityIsTransient(SaveOrUpdateEvent event) at NHibernate.Event.Default.DefaultSaveEventListener.PerformSaveOrUpdate(SaveOrUpdateEvent event) at NHibernate.Event.Default.DefaultSaveOrUpdateEventListener.OnSaveOrUpdate(SaveOrUpdateEvent event) at NHibernate.Impl.SessionImpl.FireSave(SaveOrUpdateEvent event) at NHibernate.Impl.SessionImpl.Save(Object obj) at Api.Socioboard.Model.DatabaseRepository.Add[T](T item)_"
![2](https://user-images.githubusercontent.com/32266979/31115945-1a101cc4-a831-11e7-83ce-9e39173ad9f6.png)

**Comment by socioboard** [comment]
Hi meysam ,
 contact with our support team.
email : support@socioboard.com
skype : socioboard.support

Thanks
SB team

**Comment by josfranco** [comment]
Hi!

In Domin.Socioboard/compiler/resources/Mappings need alter a build Action to Embedded Resource

I opened project in Visual Studio 2017, this setting is lost on migration

**Comment by osmanraifgunes** [comment]
Embedding all files under Domin.Socioboard/compiler/resources/Mappings as embbeded resource solved my problem : 
[how to embed ](https://stackoverflow.com/questions/42679642/how-to-embed-resource-files-at-build-in-visual-studio-2017)

**Comment by rajithagarapati** [comment]
Replace with the following code in Domain.Socioboard.csproj

<ItemGroup>
    <Compile Remove="compiler\resources\Mappings\*" />
    <EmbeddedResource Include="compiler\resources\Mappings\*" />
  </ItemGroup>

**Comment by rajithagarapati** [comment]
`<ItemGroup>
    <Compile Remove="compiler\resources\Mappings\*" />
    <EmbeddedResource Include="compiler\resources\Mappings\*" />
  </ItemGroup>`
