### ISSUE TITLE
No Manual

### ISSUE THREAD

**Issue by manashgarg** [socioboard/Socioboard-Core-3.0#44]
Hi,
I downloaded the socioboard latest release then downloaded 
Visual stuiod 2013,2015,2017 (community edition)
in all of them it says project is not compatible.
There is no good tutorial on how to begin with installation.
Is they any way that you can help on pre requirements what all we need to install
and if we get incompatible error what we are supposed to do?

CAn you please help with a text file on how to proceed 
![screen shot 2017-09-30 at 2 24 36 am](https://user-images.githubusercontent.com/1341167/31035744-b90bd0a0-a586-11e7-90cd-59f6d296b134.png)

This is the infor of my visual studio
Microsoft Visual Studio Community 2015
Version 14.0.25431.01 Update 3
Microsoft .NET Framework
Version 4.6.01055

Installed Version: Community

Visual Basic 2015   00322-20000-00000-AA767
Microsoft Visual Basic 2015

Visual C# 2015   00322-20000-00000-AA767
Microsoft Visual C# 2015

Visual C++ 2015   00322-20000-00000-AA767
Microsoft Visual C++ 2015

Application Insights Tools for Visual Studio Package   1.0
Application Insights Tools for Visual Studio

Common Azure Tools   1.8
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

NuGet Package Manager   3.4.4
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

TypeScript   1.8.36.0
TypeScript tools for Visual Studio

**Comment by socioboard** [comment]
Hi manashgarg ,
just update the software required for visual studio ,shown in notification
![image](https://user-images.githubusercontent.com/6312383/31112760-42276602-a833-11e7-8bf3-d3b02aefce29.png)

**Comment by socioboard** [comment]
Hi manashgarg ,
I hope you have found the solution for it for now am closing the bug ,
in future if you find any issue please let us know .

Thanks
SB team
