### ISSUE TITLE
Self Hosting Issue

### ISSUE THREAD

**Issue by manashgarg** [socioboard/Socioboard-Core-3.0#45]
When I finally able to run the project I tried to register after filling in all the details it says "undefined"

and one more thing I want to know even in self hosted version we have different packages?
then what is the use of self hosted version??

**Comment by socioboard** [comment]
Hi manashgarg,
can you show us the screen shot of the error.
becoz we are unable to find exact issue what you facing.

Thanks
SB Team

**Comment by socioboard** [comment]
Hi manashgarg,
i hope you have found the solution so for now am closing the issue, later if you have any issue
please let us know  .
Thanks 
SB Team
