### ISSUE TITLE
License for Socioboard?

### ISSUE THREAD

**Issue by nynymike** [socioboard/Socioboard-Core-3.0#46]
What is the license for this project? 

When I search for "license" in this project, I see that one of the plugins is actually not open source:

```
 @license Copyright (c) 2003-2014, CKSource - Frederico Knabben. All rights reserved.
```

Ideally, every single page would have the license reference on it.  And any contributor to the project should align with the license requirement. 

And the link off the main web page is broken: [https://socioboard.org/license/](https://socioboard.org/license/)

**Comment by swetasb** [comment]
Hi nynymike,
sorry for inconvenience ,now licence is available
please visit the site https://socioboard.org/license/

Thanks 
SB Team

**Comment by socioboard** [comment]
Hi nynymike,
sorry for inconvenience,
now you can see licence for the same
https://socioboard.org/license/

Thanks 
SB Team

**Comment by socioboard** [comment]
Hi nynymike,
I hope you have found the solution for now  am closing this .in future if you face any issue  let us know .
Thanks 
SB Team
