### ISSUE TITLE
Can't do login Socioboard 3.0.29

### ISSUE THREAD

**Issue by JoseEslava** [socioboard/Socioboard-Core-3.0#47]
I installed Socioboard and all technology needed, according the guide. I tried to test the socioboard community on VS Pro 2017, the first problem is login:  1. by Facebook (error message: token invalid returned from the Faceboos page) 2. by Google (debuger error message: invalid null value) 3. by Register (error message: can’t create user)

I reviewed all tokens and keys from facebook ans google developer. How can I get to login?

**Comment by socioboard** [comment]
Hi JoseEslava,
can you try with vs 2015 as we are facing some update issue in vs 2017
when it get solve will update soon.
Thanks
SB team

**Comment by socioboard** [comment]
Hi JoseEslava,
I hope you have found the solution for now am closing issue
in future if you have any issue please let us know.

Thanks
SB team
