### ISSUE TITLE
Setting up Socioboard on Windows

### ISSUE THREAD

**Issue by bvarba** [socioboard/Socioboard-Core-3.0#48]
Hi Sumit,

I like the project and I'd like to set it up and eventually contribute. 
When I try to build release Socioboard-Core-3.0-3.0.29 I get "Package Restore failed".
When I investigate I see the following packages from www.myget.org json are not available:
error: Response status code does not indicate success: 400 (Bad Request).
error: Failed to retrieve information from remote source 'https://www.myget.org/F/aspnet-contrib/api/v3/index.json&quot;/FindPackagesById()?id='Iesi.Collections''.
error:   Response status code does not indicate success: 400 (Bad Request).
log  : Retrying 'FindPackagesByIdAsyncCore' for source 'https://www.myget.org/F/aspnet-contrib/api/v3/index.json&quot;/FindPackagesById()?id='Microsoft.Bcl''.
log  : Response status code does not indicate success: 400 (Bad Request).
error: Failed to retrieve information from remote source 'https://www.myget.org/F/aspnet-contrib/api/v3/index.json&quot;/FindPackagesById()?id='TweetinviAPI''.
error: Response status code does not indicate success: 400 (Bad Request).

I tried dotnet restore in console, same thing.
I tried few months back and I was able to run it. (At the time I run in to problem setting up facebook and social media connections)
Any help appreciated for the setup of this awesome project.

Thank you,
Boris

**Comment by socioboard** [comment]
Hi bvarba,
First of all thanks for appreciation :)
for socioboard 3.0 setup you facing issue so for that i will suggest you just contact with our support team ( emailId : support@socioboard.com , skypeId : socioboard.support  ) here you can find all solution of socioboard 3.0 
one more thing we have release socioboard 3.0.30 just try once and check .if you still facing issue feel free to contact.

Thanks
SB Team

**Comment by bvarba** [comment]
Hi SB Team,

Thank you.
I'll get the new version and ask if anything on skype.

Cheers,
Boris

**Comment by bvarba** [comment]
Any update on this?

**Comment by socioboard** [comment]
Hi bvarba,
can we know the exact query what you asking ?

Thanks
SB Team

**Comment by bvarba** [comment]
Hi SB team,
when I try to compile the project (release 3.0-3.0.30) I get the following:
log  : Retrying 'FindPackagesByIdAsyncCore' for source 'https://www.myget.org/F/aspnet-contrib/api/v3/index.json&quot;/FindPackagesById()?id='PayPalCoreSDK''.
log  : Response status code does not indicate success: 400 (Bad Request).
log  : Retrying 'FindPackagesByIdAsyncCore' for source 'https://www.myget.org/F/aspnet-contrib/api/v3/index.json&quot;/FindPackagesById()?id='Iesi.Collections''.
log  : Response status code does not indicate success: 400 (Bad Request).
log  : Retrying 'FindPackagesByIdAsyncCore' for source 'https://www.myget.org/F/aspnet-contrib/api/v3/index.json&quot;/FindPackagesById()?id='PayPalMerchantSDK''.
log  : Response status code does not indicate success: 400 (Bad Request).
log  : Retrying 'FindPackagesByIdAsyncCore' for source 'https://www.myget.org/F/aspnet-contrib/api/v3/index.json&quot;/FindPackagesById()?id='Imgur.API''.
log  : Response status code does not indicate success: 400 (Bad Request).
log  : Retrying 'FindPackagesByIdAsyncCore' for source 'https://www.myget.org/F/aspnet-contrib/api/v3/index.json&quot;/FindPackagesById()?id='RestApiSDK''.
log  : Response status code does not indicate success: 400 (Bad Request).
log  : Retrying 'FindPackagesByIdAsyncCore' for source 'https://www.myget.org/F/aspnet-contrib/api/v3/index.json&quot;/FindPackagesById()?id='MongoDB.Driver''.
log  : Response status code does not indicate success: 400 (Bad Request).
log  : Retrying 'FindPackagesByIdAsyncCore' for source 'https://www.myget.org/F/aspnet-contrib/api/v3/index.json&quot;/FindPackagesById()?id='PayPalMerchantSDK''.
log  : Response status code does not indicate success: 400 (Bad Request).
log  : Retrying 'FindPackagesByIdAsyncCore' for source 'https://www.myget.org/F/aspnet-contrib/api/v3/index.json&quot;/FindPackagesById()?id='RestApiSDK''.
log  : Response status code does not indicate success: 400 (Bad Request).
log  : Retrying 'FindPackagesByIdAsyncCore' for source 'https://www.myget.org/F/aspnet-contrib/api/v3/index.json&quot;/FindPackagesById()?id='Iesi.Collections''.
log  : Response status code does not indicate success: 400 (Bad Request).
log  : Retrying 'FindPackagesByIdAsyncCore' for source 'https://www.myget.org/F/aspnet-contrib/api/v3/index.json&quot;/FindPackagesById()?id='PayPalCoreSDK''.
log  : Response status code does not indicate success: 400 (Bad Request).
log  : Retrying 'FindPackagesByIdAsyncCore' for source 'https://www.myget.org/F/aspnet-contrib/api/v3/index.json&quot;/FindPackagesById()?id='Imgur.API''.
log  : Response status code does not indicate success: 400 (Bad Request).
log  : Retrying 'FindPackagesByIdAsyncCore' for source 'https://www.myget.org/F/aspnet-contrib/api/v3/index.json&quot;/FindPackagesById()?id='MongoDB.Driver''.
log  : Response status code does not indicate success: 400 (Bad Request).
error: Failed to retrieve information from remote source 'https://www.myget.org/F/aspnet-contrib/api/v3/index.json&quot;/FindPackagesById()?id='RestApiSDK''.
error: Response status code does not indicate success: 400 (Bad Request).
error: Failed to retrieve information from remote source 'https://www.myget.org/F/aspnet-contrib/api/v3/index.json&quot;/FindPackagesById()?id='Iesi.Collections''.
error: Response status code does not indicate success: 400 (Bad Request).
error: Failed to retrieve information from remote source 'https://www.myget.org/F/aspnet-contrib/api/v3/index.json&quot;/FindPackagesById()?id='Iesi.Collections''.
error:   Response status code does not indicate success: 400 (Bad Request).
error: Failed to retrieve information from remote source 'https://www.myget.org/F/aspnet-contrib/api/v3/index.json&quot;/FindPackagesById()?id='PayPalMerchantSDK''.
error: Response status code does not indicate success: 400 (Bad Request).
error: Failed to retrieve information from remote source 'https://www.myget.org/F/aspnet-contrib/api/v3/index.json&quot;/FindPackagesById()?id='PayPalCoreSDK''.
error: Response status code does not indicate success: 400 (Bad Request).
error: Failed to retrieve information from remote source 'https://www.myget.org/F/aspnet-contrib/api/v3/index.json&quot;/FindPackagesById()?id='Imgur.API''.
error: Response status code does not indicate success: 400 (Bad Request).
log  : Retrying 'FindPackagesByIdAsyncCore' for source 'https://www.myget.org/F/aspnet-contrib/api/v3/index.json&quot;/FindPackagesById()?id='TweetinviAPI''.
log  : Response status code does not indicate success: 400 (Bad Request).
error: Failed to retrieve information from remote source 'https://www.myget.org/F/aspnet-contrib/api/v3/index.json&quot;/FindPackagesById()?id='MongoDB.Driver''.
error: Response status code does not indicate success: 400 (Bad Request).

**Comment by socioboard** [comment]
please update the require package given in notification

**Comment by socioboard** [comment]
Hi bvarba ,
I hope u have found the solution  ,
in future if u face any issue  open this ticket again .

Thanks
SB Team

**Comment by bvarba** [comment]
Hi SB Team,

No it is not resolved. How can I restore/update the packages from the errors?
When I do Nuget restore from Visual Studio or dotnet restore from command line I get the above errors. If I look at index.json from the link it is trying to find them from: https://www.myget.org/F/aspnet-contrib/api/v3/index.json I see they are not listed in this file.

I will reopen the ticket as I really want to get this awesome project running.

Thank you for your help,
Boris
