### ISSUE TITLE
Missing AppSetting properties: Build failure in latest release

### ISSUE THREAD

**Issue by bohece** [socioboard/Socioboard-Core-3.0#49]
The latest release(Socioboard 3.0.30) does not compile.
It has missing properties in AppSettings.
Properties like googleClientId, googleClientSecret and many other settings are used in DataService and other projects but are not available in AppSettings class.
Moreover, there is "LiveMongoDbConnectionString" which not available anywhere in the project.
It seems few changes are remaining to be committed in the latest release.

Let me know if I can help and can make a PR and commit.

**Comment by socioboard** [comment]
Hi bohece,
actually you are not taking latest code from github so i will suggest you to take
it from mentioned path : https://github.com/socioboard/Socioboard-Core-3.0/archive/v3.0.30.zip 
for appsetting : you have to set your own appsetting and credentials in code .
further ,if you facing issue again please feel free to contact us at given 
emailId : support@socioboard.com
skype : socioboard.support.

Thanks 
SB Team

**Comment by bohece** [comment]
I am have cloned the latest code from github
This is the link I used https://github.com/socioboard/Socioboard-Core-3.0/archive/v3.0.30.zip
If you search for LiveMongoDbConnectionString, googleClientId, googleClientSecret  etc in code even here on Github you'll see what I am saying.
There are no variables with these names in AppSettings nor in appSettings.json and are used at many places.
![devenv_2017-10-27_11-42-39](https://user-images.githubusercontent.com/32789550/32090258-1fec5f70-bb0c-11e7-8cd2-7b5686eb03b2.png)
![devenv_2017-10-27_11-43-08](https://user-images.githubusercontent.com/32789550/32090259-204068d6-bb0c-11e7-84d8-e994fc80b7db.png)

**Comment by socioboard** [comment]
Hi bohece,
for that you just add your own variables and credentials if you dont need it then commnet the code and check.

**Comment by bohece** [comment]
Sorry, but I am not sure if you understood it correctly.
I have changed the keys, secrets and connectionString as per my environment.
But, it is a compile time error in the solution. There are no variables with these names LiveMongoDbConnectionString, googleClientId, googleClientSecret in AppSettings as shown in my previous screenshot.
And, these are used at many places as shown below.
![image](https://user-images.githubusercontent.com/32789550/32092217-1e1a3ad8-bb15-11e7-8ea7-7504b3733d71.png)

**Comment by socioboard** [comment]
can you see namespace given in image just go to the path or press f12 over Appsettings. it can open the actual location of that file.
![image](https://user-images.githubusercontent.com/6312383/32093666-debfda90-bb1a-11e7-87d7-0c2a58f617bb.png)

**Comment by bohece** [comment]
Hi,
That's Correct. I am talking about this file. As you can see in your screenshot it does not contain properties like LiveMongoDbConnectionString, googleClientId, googleClientSecret etc which are used in classes GooglePlusDataService, YtDataService etc

**Comment by socioboard** [comment]
just add that variable  which has not shown in appsetting
![image](https://user-images.githubusercontent.com/6312383/32101280-3349951e-bb35-11e7-8601-eac81211db9c.png)

**Comment by bohece** [comment]
Thanks
