### ISSUE TITLE
Publishing error in web api

### ISSUE THREAD

**Issue by maksudcs** [socioboard/Socioboard-Core-3.0#5]
Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not find a part of the path 'E:\Socioboard-Core-3.0-master\Socioboard-Core-3.0-master\src\Api.Socioboard\bin\Release\net451\win\Api.Socioboard.exe'.	Api.Socioboard		0	
![error](https://cloud.githubusercontent.com/assets/17357327/22620676/234c0504-eb3b-11e6-8485-458ee4895bae.png)

**Comment by maksudcs** [comment]
please take a look..

**Comment by maksudcs** [comment]
any one please help me .. its very urgent..

**Comment by socioboard** [comment]
Hi Maksudcs,
Please delete data from bin folder
path- api.socioboard->bin

then clean and rebuild solution

**Comment by maksudcs** [comment]
no solved.

**Comment by maksudcs** [comment]
project.json file


{
  "dependencies": {
    "Domain.Socioboard": "1.0.0-*",
    "Microsoft.AspNetCore.Mvc": "1.0.0",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
    "Microsoft.Extensions.Configuration.FileExtensions": "1.0.0",
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
    "Microsoft.Extensions.Logging": "1.0.0",
    "Microsoft.Extensions.Logging.Console": "1.0.0",
    "Microsoft.Extensions.Logging.Debug": "1.0.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0",
    "Socioboard.Facebook": "1.0.0-*",
    "Socioboard.Google": "1.0.0-*",
    "Socioboard.Instagram": "1.0.0-*",
    "Socioboard.LinkedIn": "1.0.0-*",
    "Socioboard.Twitter": "1.0.0-*",
    "Serilog": "2.1.0",
    "Serilog.Extensions.Logging": "1.1.0",
    "Serilog.Sinks.ColoredConsole": "2.0.0",
    "Serilog.Sinks.RollingFile": "2.1.0",
    "Microsoft.Extensions.Options": "1.0.0",
    "MongoDB.Driver": "2.2.4",
    "MySql.Data": "6.9.8",
    "MySql.Data.Entity": "6.9.8",
    "Newtonsoft.Json": "9.0.1",
    "NHibernate.Linq": "1.0.0",
    "StackExchange.Redis": "1.1.603",
    "Google.Apis.Analytics.v3": "1.14.0.456",
    "Microsoft.AspNetCore.Cors": "1.0.0",
    "MongoDB.Bson": "2.2.4",
    "Microsoft.AspNetCore.Diagnostics": "1.0.0",
    "System.Drawing.Primitives": "4.0.0",
    "Swashbuckle.SwaggerGen": "6.0.0-beta901",
    "Swashbuckle.SwaggerUi": "6.0.0-beta901",
    "Microsoft.ApplicationInsights.AspNetCore": "1.0.2"
  },

  "tools": {
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final"
  },

  "frameworks": {
    "net451": {
      "frameworkAssemblies": {
        "System.Xml": "4.0.0.0"
      },
      "dependencies": {
        "NHibernate": "4.0.4.4000"
      }
    }
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true,
    "xmlDoc": false
  },
  "runtimes": { "win": [ "win7-x64", "win8-x64", "win10-x64" ] },
  "runtimeOptions": {
    "configProperties": {
      "System.GC.Server": true
    }
  },

  "publishOptions": {
    "include": [
      "wwwroot"
    ]
  },

  "scripts": {
     "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  }
}

**Comment by maksudcs** [comment]
Web Publishing activity:

rmdir /S /Q "C:\Users\bITS\AppData\Local\Temp\PublishTemp\Api.Socioboard47\"
Environment variables:
Path=.\node_modules\.bin;G:\Program Files (x86)\Web\External;%PATH%;G:\Program Files (x86)\Web\External\git
C:\Program Files (x86)\dotnet\dotnet.exe publish "E:\Work\src\Api.Socioboard" --framework net451 --runtime win --output "C:\Users\bITS\AppData\Local\Temp\PublishTemp\Api.Socioboard47" --configuration Release --no-build
Publishing Api.Socioboard for .NETFramework,Version=v4.5.1/win
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Publishing.targets(149,5): Error : Could not find a part of the path 'E:\Work\src\Api.Socioboard\bin\Release\net451\win\Api.Socioboard.exe'.

**Comment by swetk5** [comment]
Hi maksudcs ,
1 . Please install this in your project using NuGet Package Manager :   
 DotNetCore.1.0.1-SDK.1.0.0.Preview2-003133-x86

2. Do modification in global json  i.e "version": "1.0.0-preview2-003131"

Thanks

**Comment by socioboard** [comment]
Hi maksudcs ,
1 . Please install this in your project :   
 DotNetCore.1.0.1-SDK.1.0.0.Preview2-003133-x86

2. Do modification in global json  i.e "version": "1.0.0-preview2-003131"

Thanks

**Comment by maksudcs** [comment]
i have changed , but result is same

**Comment by socioboard** [comment]
Hi maksudcs,
Can you provide proper screen shot and details for your issue. when and in which you getting this error.
or else you can provide your skype id for remote access.

Thanks
Socioboard Team

**Comment by maksudcs** [comment]
just comment previous and add below settings:

  "runtimeOptions": {
    "configProperties": {
      "System.GC.Server": true
    }
  },

that solved my publish problem.

**Comment by kasidesh** [comment]
Hi maksucks
    Can you specify more detail on your last comment?

> just comment previous and add below settings:

I checked in the project.json it's already has these line of code.

"runtimeOptions": {
"configProperties": {
"System.GC.Server": true
}
},

**Comment by maksudcs** [comment]
hi kasidesh ,

i have changed below this


  //"runtimes": { "win": [ "win7-x64", "win8-x64", "win10-x64" ] },
  //"runtimeOptions": {
  //  "configProperties": {
  //    "System.GC.Server": true
  //  }
  //},
  "runtimeOptions": {
    "configProperties": {
      "System.GC.Server": true
    }
  },

i just comment runtimes properties..
