### ISSUE TITLE
Project setup

### ISSUE THREAD

**Issue by bvarba** [socioboard/Socioboard-Core-3.0#50]
Hi SB Team,

No it is not resolved yet. How can I restore/update the packages from the errors?
When I do Nuget restore from Visual Studio or dotnet restore from command line I get the above errors. If I look at index.json from the link it is trying to find them from: https://www.myget.org/F/aspnet-contrib/api/v3/index.json I see they are not listed in this file.
Do I have to be signed up on myget.org? I did make an account. What am I missing?
I am making a new ticket as I really want to get this awesome project running. Please do not close it until the project is up an running.

Thank you for your help, I really appreciate it,
Boris

Here are the errors and packages:
log : Retrying 'FindPackagesByIdAsyncCore' for source 'https://www.myget.org/F/aspnet-contrib/api/v3/index.json&quot;/FindPackagesById()?id='PayPalCoreSDK''.
log : Response status code does not indicate success: 400 (Bad Request).
log : Retrying 'FindPackagesByIdAsyncCore' for source 'https://www.myget.org/F/aspnet-contrib/api/v3/index.json&quot;/FindPackagesById()?id='Iesi.Collections''.
log : Response status code does not indicate success: 400 (Bad Request).
log : Retrying 'FindPackagesByIdAsyncCore' for source 'https://www.myget.org/F/aspnet-contrib/api/v3/index.json&quot;/FindPackagesById()?id='PayPalMerchantSDK''.
log : Response status code does not indicate success: 400 (Bad Request).
log : Retrying 'FindPackagesByIdAsyncCore' for source 'https://www.myget.org/F/aspnet-contrib/api/v3/index.json&quot;/FindPackagesById()?id='Imgur.API''.
log : Response status code does not indicate success: 400 (Bad Request).
log : Retrying 'FindPackagesByIdAsyncCore' for source 'https://www.myget.org/F/aspnet-contrib/api/v3/index.json&quot;/FindPackagesById()?id='RestApiSDK''.
log : Response status code does not indicate success: 400 (Bad Request).
log : Retrying 'FindPackagesByIdAsyncCore' for source 'https://www.myget.org/F/aspnet-contrib/api/v3/index.json&quot;/FindPackagesById()?id='MongoDB.Driver''.
log : Response status code does not indicate success: 400 (Bad Request).
log : Retrying 'FindPackagesByIdAsyncCore' for source 'https://www.myget.org/F/aspnet-contrib/api/v3/index.json&quot;/FindPackagesById()?id='PayPalMerchantSDK''.
log : Response status code does not indicate success: 400 (Bad Request).
log : Retrying 'FindPackagesByIdAsyncCore' for source 'https://www.myget.org/F/aspnet-contrib/api/v3/index.json&quot;/FindPackagesById()?id='RestApiSDK''.
log : Response status code does not indicate success: 400 (Bad Request).
log : Retrying 'FindPackagesByIdAsyncCore' for source 'https://www.myget.org/F/aspnet-contrib/api/v3/index.json&quot;/FindPackagesById()?id='Iesi.Collections''.
log : Response status code does not indicate success: 400 (Bad Request).
log : Retrying 'FindPackagesByIdAsyncCore' for source 'https://www.myget.org/F/aspnet-contrib/api/v3/index.json&quot;/FindPackagesById()?id='PayPalCoreSDK''.
log : Response status code does not indicate success: 400 (Bad Request).
log : Retrying 'FindPackagesByIdAsyncCore' for source 'https://www.myget.org/F/aspnet-contrib/api/v3/index.json&quot;/FindPackagesById()?id='Imgur.API''.
log : Response status code does not indicate success: 400 (Bad Request).
log : Retrying 'FindPackagesByIdAsyncCore' for source 'https://www.myget.org/F/aspnet-contrib/api/v3/index.json&quot;/FindPackagesById()?id='MongoDB.Driver''.
log : Response status code does not indicate success: 400 (Bad Request).
error: Failed to retrieve information from remote source 'https://www.myget.org/F/aspnet-contrib/api/v3/index.json&quot;/FindPackagesById()?id='RestApiSDK''.
error: Response status code does not indicate success: 400 (Bad Request).
error: Failed to retrieve information from remote source 'https://www.myget.org/F/aspnet-contrib/api/v3/index.json&quot;/FindPackagesById()?id='Iesi.Collections''.
error: Response status code does not indicate success: 400 (Bad Request).
error: Failed to retrieve information from remote source 'https://www.myget.org/F/aspnet-contrib/api/v3/index.json&quot;/FindPackagesById()?id='Iesi.Collections''.
error: Response status code does not indicate success: 400 (Bad Request).
error: Failed to retrieve information from remote source 'https://www.myget.org/F/aspnet-contrib/api/v3/index.json&quot;/FindPackagesById()?id='PayPalMerchantSDK''.
error: Response status code does not indicate success: 400 (Bad Request).
error: Failed to retrieve information from remote source 'https://www.myget.org/F/aspnet-contrib/api/v3/index.json&quot;/FindPackagesById()?id='PayPalCoreSDK''.
error: Response status code does not indicate success: 400 (Bad Request).
error: Failed to retrieve information from remote source 'https://www.myget.org/F/aspnet-contrib/api/v3/index.json&quot;/FindPackagesById()?id='Imgur.API''.
error: Response status code does not indicate success: 400 (Bad Request).
log : Retrying 'FindPackagesByIdAsyncCore' for source 'https://www.myget.org/F/aspnet-contrib/api/v3/index.json&quot;/FindPackagesById()?id='TweetinviAPI''.
log : Response status code does not indicate success: 400 (Bad Request).
error: Failed to retrieve information from remote source 'https://www.myget.org/F/aspnet-contrib/api/v3/index.json&quot;/FindPackagesById()?id='MongoDB.Driver''.
error: Response status code does not indicate success: 400 (Bad Request).

**Comment by socioboard** [comment]
Hello bvarba,

Thanks for reporting this and for your patience, We're sorry that you faced issue with this, We'll help you for this so kindly follow these following steps.

- You have to install the packages from **nuget** in which you got issues
- Simply goto **Visual Studio** > **Tools** > **NuGet Package Manager**> **Manage NuGet packages for solution**
- After this you have to type the name of the packages in which you got issue then install the respective package

This will definitely sort out the issue

Thanks
Socioboard team

**Comment by socioboard** [comment]
Hello bvarba,
I hope you have found your solution, closing this issue for now if you find any prob just reopen it. 


Thanks
SB Team
