### ISSUE TITLE
Socioboard Setup Issue!

### ISSUE THREAD

**Issue by shaiksultan** [socioboard/Socioboard-Core-3.0#52]
After setup the project in VS Studio 2013 , Hit  Run i am getting message values.json open, then application crashes. Howe ever i can see the application running for sometime 
Please support is there any run time available for community version just click to continue?
Any other steps missing?

**Comment by socioboard** [comment]
Hi shaiksultan,
Project will run on vs 2015 ,it will not work with earlier version.
download vs 2015 and run the project. if you face any issue please let us know.

Thanks
SB Team

**Comment by shaiksultan** [comment]
Sorry its VS 2015 , I am getting this Message values.json

**Comment by shaiksultan** [comment]
Please update

**Comment by socioboard** [comment]
can you show screen shot of issue in your code

**Comment by shaiksultan** [comment]
1 ) Please find the attached screen shot when we run the app from VS 2015  IE the message displays

2) If we run Chrome The app run once you hit login , Trail Expired and also app  closes itself
Sometimes your trail has expired you can not use [paid](url
![capture](https://user-images.githubusercontent.com/13413656/34037076-de4a0e1c-e1a0-11e7-9aa3-9468fc29ac87.PNG)
) services

**Comment by socioboard** [comment]
can not see what the exact issue you facing please provide the desktop remote access to see the problem in your code

**Comment by socioboard** [comment]
Its not error i.e value.json it come when you run in IE and the second one in db have to change from free plan to any paid plan

**Comment by shaiksultan** [comment]
Dear  Mr Sumit,

682 958 502
9686

**Comment by shaiksultan** [comment]
where do you specify access token face book config?
i am getting invalid access token authentication using facebook

**Comment by socioboard** [comment]
you have to give your register facebook app access token .

**Comment by socioboard** [comment]
Hi shaiksultan,
I hope you have found the solution n doing well,
for now am closing this issue, in future if you face same reopen it .

Thanks
SB Team
