### ISSUE TITLE
validation emal

### ISSUE THREAD

**Issue by cyberprosconsulting** [socioboard/Socioboard-Core-3.0#53]
i can't seem to figure out why the validation email isn't being sent via the zoho i've followed the instructions and when signup it says email sent but then nothing comes in please advise

**Comment by socioboard** [comment]
Hi cyberprosconsulting ,
can you provide email id with which you have created the account.

**Comment by socioboard** [comment]
Hi cyberprosconsulting ,
are you using project or software .if you using project code then 
add your zoho creds in appsetting. if still error persist let us know

Thanks
SB Team

**Comment by cyberprosconsulting** [comment]
i'm using the v3 code from github right here and i've added my zoho creds and still not working

**Comment by socioboard** [comment]
can you show the screen shot of the error

**Comment by cyberprosconsulting** [comment]
thats the thing i'm not showing an error it says its successfully sent the email but the email never comes

**Comment by socioboard** [comment]
its problem with check zoho account create new and check .

**Comment by cyberprosconsulting** [comment]
checking now

**Comment by cyberprosconsulting** [comment]
just checking something does it have to be a zoho business account or a personal account or either?

**Comment by socioboard** [comment]
yes

**Comment by cyberprosconsulting** [comment]
yes to which

**Comment by socioboard** [comment]
zoho business mail account try with that

**Comment by cyberprosconsulting** [comment]
k that might have been the problem cause i just used the @zoho.com personal account

**Comment by cyberprosconsulting** [comment]
k did that still says email sent but no email comes in

**Comment by socioboard** [comment]
we have proper setup for mail sending once google it  you can find the solution .maybe problem with zoho try with other mail site.

**Comment by cyberprosconsulting** [comment]
can i use gmail? if so please advise what i need to change in coding

**Comment by cyberprosconsulting** [comment]
or can i use my own mail servers?

**Comment by cyberprosconsulting** [comment]
well i've tried it with my servers as well and there is no mail going to my email server

**Comment by cyberprosconsulting** [comment]
ok so this is where i'm at socioboard 2.0.32 send email with either gmail or zoho if i change the gmail smtp to the zoho smtp and i recieve the email with no problem.

version 3.0.37 claims it's sending the email but no email comes

this being said so what is the problem with v3 cause it's not a zoho thing it's not a gmail thing it's not a firewall issue it's a v3.0.37 issue

for v3.0.37 i've added my zoho.com credentials into the appsettings.json file like instructed all should work  from there but it does not

**Comment by socioboard** [comment]
can you download file from this url :   "https://github.com/socioboard/socioboard-core"

**Comment by cyberprosconsulting** [comment]
this is version 2 of socioboard. i have version 2.0.32 working sending email already. it's version 3 that isn't working

**Comment by socioboard** [comment]
ok let us check the version issue will update u soon regarding latest version

**Comment by cyberprosconsulting** [comment]
ok while your checking on v3 in version 2 i can't seem to figure out how to get it to use a domain. i changed everything the docs say but it still comes up localhost instead of the domain name

**Comment by socioboard** [comment]
Hi ,
There is no problem in version can you check agiain your setup or give us skype mail id for remote access.
ping them for support: socioboard.support

**Comment by socioboard** [comment]
Hi cyberprosconsulting,
I hope you have found the solution n doing well.
for now am closing this issue. in  future you can reopen it for further query with same. 

Thanks
SB Team

**Comment by alshaikh1** [comment]
I have the same problem. I'm using version 3. when a user signs up by email, no email is being received. any suggestion?

**Comment by cyberprosconsulting** [comment]
Yes find another program after getting this one working the limitations it had were not what they claimed it could do. About the only think usable was facebook and twitter.

 

 

Best Regards,

 

Bradley Charles

CEO

Cyber Pros Consulting

1 (647) 931-1793 ext 206

 <http://www.cyberprosconsulting.com> www.cyberprosconsulting.com

 <mailto:bradley@cyberprosconsulting.com> bradley@cyberprosconsulting.com
