### ISSUE TITLE
online at my server it gives 500 interval server error .

### ISSUE THREAD

**Issue by pehelle** [socioboard/Socioboard-Core-3.0#58]
hi download you product it installed in my local  it is good here . when i moved it to my server goiworld.org
it gives 500 interval server error please assist me .

Regards 
Mahesh Malik
9891383126

**Comment by socioboard** [comment]
Hi pehelle,
have done proper configuration in your server .if you miss little thing, it will show 500 error that is from server side issue.please check once .

**Comment by pehelle** [comment]
can i know what should we need to  installed on server . or other config setting required for

**Comment by socioboard** [comment]
can't say have to see your server where u getting issue.

**Comment by socioboard** [comment]
Hi pehelle,
I hope you have found your solution for now am closing this issue ,in future if any  problem 
please let us know.

Thanks
SB Team
