### ISSUE TITLE
link to Facebook

### ISSUE THREAD

**Issue by thsaing1** [socioboard/Socioboard-Core-3.0#59]
Hi

Once project is run, SIGNIN --> Sign-in with Facebook --> enter facebook id/pwd --> route to below link and stop. Pls help. Thanks in advance..

http://localhost:9821/#_=_

Regards,
Tin

**Comment by thsaing1** [comment]
Adding for above. Already configure facebook id/secret in Socioboard. Thks

**Comment by socioboard** [comment]
Hi thsaing1,
please add connection string in your code.

**Comment by socioboard** [comment]
Hi thsaing1,
I hope you have found your solution if any problem please let us know.

Thanks
SB Team
