### ISSUE TITLE
Any one deploy socioboard in amazon web server (AWS) ?

### ISSUE THREAD

**Issue by maksudcs** [socioboard/Socioboard-Core-3.0#6]
I have deployed project in amazon AWS with .Net AWS Tools. below my link:

http://socioboard-dev.us-east-1.elasticbeanstalk.com/

But problem is that, i did not connect with MySql dbinstance thats why can not make login, registration.
if any one do this, please suggest.

Thanks

**Comment by maksudcs** [comment]
yes. use RDS for mysql database.

**Comment by socioboard** [comment]
have you allowed inbound and outbound connections in security group of that instance?
means is it in available state?
1. check whether the instance is in available state 
2. check the security group of that instance for inbound and outbound
