### ISSUE TITLE
Mobile Apps IOS and Android 

### ISSUE THREAD

**Issue by garshom** [socioboard/Socioboard-Core-3.0#60]
Hello Team, 

I see like official mobile apps for iOS and Android are available but I don't see any direction to their sources,   any advise on how to get the source for mobile apps for socioboard core-3.0

Thanks
Garshom

**Comment by socioboard** [comment]
Hi garshom,
just go through this link  :
https://itunes.apple.com/sg/app/socioboard/id923398550?mt=8

**Comment by socioboard** [comment]
Hi garshom,
I hope you have solved your problem for now am closing this issue ,if any query 
please let us know. 

Thanks
SB Team
