### ISSUE TITLE
Invaild Access Token (FB), Access token not found (GG)

### ISSUE THREAD

**Issue by gnh1201** [socioboard/Socioboard-Core-3.0#61]
I was received "Invaild Access Token (FB)/Access token not found (GG)" messages
from redirect URI (ex: http://localhost:9821/*Manager/*) of socioboard.

Status of Application ID, Secret and App Key is everything ok in appsetting.json (SB API and SB)

How to find logs or debug info (related to Access Token Errors) for fix this issue?

**Comment by gnh1201** [comment]
See also: http://exts.kr/wiki/doku.php?id=socioboard-3

**Comment by socioboard** [comment]
jsut go to api > wwwroot folder in that log file will be available .

**Comment by socioboard** [comment]
Hi gnh1201,
I hope you have found the solution for it .
For now am closing this issue if any prob in future let us know

Thanks
SB Team

**Comment by arvs47** [comment]
# #

**Comment by arvs47** [comment]
#84
