### ISSUE TITLE
What is SavedFeedsComment?

### ISSUE THREAD

**Issue by gnh1201** [socioboard/Socioboard-Core-3.0#62]
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'SavedFeedsComments' could not be found (are you missing a using directive or an assembly reference?)	Api.Socioboard	C:\Socioboard-Core-3.0\src\Api.Socioboard\Controllers\SavedFeedsManagementController.cs	47	Active
Error	CS0246	The type or namespace name 'SavedFeedsComments' could not be found (are you missing a using directive or an assembly reference?)	Api.Socioboard	C:\Socioboard-Core-3.0\src\Api.Socioboard\Repositories\SavedFeedsManagementRepository.cs	30	Active
Error	CS0234	The type or namespace name 'SavedFeedsComments' does not exist in the namespace 'Domain.Socioboard.Models.Mongo' (are you missing an assembly reference?)	Api.Socioboard	C:\Socioboard-Core-3.0\src\Api.Socioboard\Repositories\SavedFeedsManagementRepository.cs	38	Active
Error	CS0246	The type or namespace name 'SavedFeedsManagement' could not be found (are you missing a using directive or an assembly reference?)	Api.Socioboard	C:\Socioboard-Core-3.0\src\Api.Socioboard\Controllers\SavedFeedsManagementController.cs	40	Active
Error	CS0246	The type or namespace name 'SavedFeedsManagement' could not be found (are you missing a using directive or an assembly reference?)	Api.Socioboard	C:\Socioboard-Core-3.0\src\Api.Socioboard\Repositories\SavedFeedsManagementRepository.cs	14	Active
Error	CS0234	The type or namespace name 'SavedFeedsManagement' does not exist in the namespace 'Domain.Socioboard.Models.Mongo' (are you missing an assembly reference?)	Api.Socioboard	C:\Socioboard-Core-3.0\src\Api.Socioboard\Repositories\SavedFeedsManagementRepository.cs	78	Active
Error	CS0234	The type or namespace name 'SavedFeedsManagement' does not exist in the namespace 'Domain.Socioboard.Models.Mongo' (are you missing an assembly reference?)	Api.Socioboard	C:\Socioboard-Core-3.0\src\Api.Socioboard\Repositories\SavedFeedsManagementRepository.cs	21	Active
Error	CS0234	The type or namespace name 'SavedFeedsManagement' does not exist in the namespace 'Domain.Socioboard.Models.Mongo' (are you missing an assembly reference?)	Api.Socioboard	C:\Socioboard-Core-3.0\src\Api.Socioboard\Repositories\SavedFeedsManagementRepository.cs	83	Active
Error	CS0234	The type or namespace name 'SavedFeedsManagement' does not exist in the namespace 'Domain.Socioboard.Models.Mongo' (are you missing an assembly reference?)	Api.Socioboard	C:\Socioboard-Core-3.0\src\Api.Socioboard\Repositories\SavedFeedsManagementRepository.cs	85	Active
Error	CS0234	The type or namespace name 'SavedFeedsManagement' does not exist in the namespace 'Domain.Socioboard.Models.Mongo' (are you missing an assembly reference?)	Api.Socioboard	C:\Socioboard-Core-3.0\src\Api.Socioboard\Repositories\SavedFeedsManagementRepository.cs	90	Active

**Comment by gnh1201** [comment]
See also: http://exts.kr/wiki/doku.php?id=socioboard-3

**Comment by socioboard** [comment]
Hi gnh1201,
download the file again from given path n check ,if any issue let us know .
https://github.com/socioboard/Socioboard-Core-3.0.git

Thnaks
SB Team

**Comment by socioboard** [comment]
Hi gnh1201,
I hope you have found the solution for it .
For now am closing this issue if any prob in future let us know

Thanks
SB Team
