### ISSUE TITLE
Script (missing assembly reference) and dnx451 error 

### ISSUE THREAD

**Issue by Nerlekar** [socioboard/Socioboard-Core-3.0#64]
Hi  Team,

We have downloaded the project called Socioboard-Core-3.0 and run the solution file and got attached error.

Can you please tell us , how to resolve the issue. 

Your urgent assistance is appreciated.

Thanks and Regards,
Gaurish Nerlekar

[Socioboardsolution error.docx](https://github.com/socioboard/Socioboard-Core-3.0/files/1707385/Socioboardsolution.error.docx)

**Comment by socioboard** [comment]
Hi Nerlekar,
we are sorry for inconvenience .
let us check the issue will update you soon 

Thanks 
SB Team

**Comment by socioboard** [comment]
can you run the project in vs 2015 and check.

**Comment by Nerlekar** [comment]
I fixed this one. I replace the dnx with net. 

So it should be net451 in targeted framework tag

**Comment by socioboard** [comment]
its great  :)  ,so i will close this issue for now .
