### ISSUE TITLE
NHibernate redis issue while Inserting records in to mysql

### ISSUE THREAD

**Issue by Nerlekar** [socioboard/Socioboard-Core-3.0#65]
Hi Team,

I am getting an error while inserting records in to MYSQL DB. I am getting all data but its not inserting in to the DB.

**Error is :** No persister for: Domain.Socioboard.Models.User

**Source Code:** 

File : database repository in Api.SocioBoard

 public int Add<T>(T item) where T : class, new()
        {
            int result = 0;
            try
            {
                using (NHibernate.ISession session = SessionFactory.GetNewSession(_env))
                {
                    using (NHibernate.ITransaction transaction = session.BeginTransaction())
                    {
                        session.Save(item);  ---- **Here is the error** 
                        transaction.Commit();
                        result = 1;
                    }

Can you please let me know how to solve this error.

Regards,
Gaurish Nerlekar

**Comment by socioboard** [comment]
have you given proper connection string ?

**Comment by Nerlekar** [comment]
Yes. We have given in heildsql config file of Api.socioboard. But still issue is same.

**Comment by socioboard** [comment]
have to check your code where you missing 
need to take remote access for that.

**Comment by Nerlekar** [comment]
Hi,

Here is the connection string we are using. Do we need to define any setting for redis connection. 
**Connection String.**. are we missing any settings in below string?

**Data Source=localhost;User ID=root;Password=sa1234;persist security info=False;initial catalog=socioboard3;pooling=true;charset=utf8; port=3306;**   

Regards,
Gaurish Nerlekar

**Comment by socioboard** [comment]
can't say what is the exact problem without seeing your code .

**Comment by socioboard** [comment]
Hi Nerlekar,
I hope you have found the solution for now am closing the issue .
if any problem further let us know.

Thanks
SB Team
