### ISSUE TITLE
Exception on dashboard loading

### ISSUE THREAD

**Issue by alshaikh1** [socioboard/Socioboard-Core-3.0#66]
I'm getting an exception just after the login and loading the dashboard. the images below show the exception and the dashboard. and I don't want to use any social media platform except Facebook.

Windows 2008 Server
Visual Studio 2015 Community

<img width="803" alt="dashboard" src="https://user-images.githubusercontent.com/8459043/36870948-457b81c6-1da9-11e8-86f5-bdcd56b1f574.PNG">

<img width="692" alt="error" src="https://user-images.githubusercontent.com/8459043/36870969-51037684-1da9-11e8-80bd-3150fe22cf9b.PNG">

**Comment by socioboard** [comment]
Hi alshaikh1,
which you don't want comment that and build the code

Thanks

**Comment by alshaikh1** [comment]
OK I will try that and let you know the results.

**Comment by socioboard** [comment]
Hi alshaikh1,
I hope you have found your solution for now am closing this issue
in future if you facing prob for same pls let us know .

Thanks
SB Team

**Comment by sstellini** [comment]
Hi,
I also came across the same problem and solved it by commenting out 2 procedures in Api.Socioboard.Controller file: 
•	GetYtGroupChannel and
•	GetYtYourGroups

thanks for the help! :-)
Sonja
