### ISSUE TITLE
Socialboard build errors 

### ISSUE THREAD

**Issue by darshandelogico** [socioboard/Socioboard-Core-3.0#67]
I downloaded project folder from [https://github.com/socioboard/Socioboard-Core-3.0](url)

I try to clean and rebuild the project but it through an error of .net / .net core target framework misconfiguration as shown in given screenshot.
![socioboard-error](https://user-images.githubusercontent.com/37323885/37326448-3982455e-26b8-11e8-9a80-9c1f37b69c2d.png)

I m using VS 2017 and .Net Core 2.1.4. please let me know if there is compulsory prerequisites also guide me how can I resolve this errors.

Thanks

**Comment by socioboard** [comment]
Hi  darshandelogico,
once change the framework version from  4.5.1 to  4.5.2 and check

Thanks

**Comment by alshaikh1** [comment]
try: visual studio 2013/2015 .

**Comment by Vegeta27** [comment]
@darshandelogico I have the same problem when compiling, I would appreciate it if you shared the solution.

**Comment by socioboard** [comment]
Hi darshandelogico,
I hope you have found your solution. for vs  2015 it works fine and for vs 2017 use latest framework version i.e after 4.5.1 its better .
for now am closing this issue if you have any problem regarding socioboard code let us know

Thanks
SB Team
