### ISSUE TITLE
Facebook Invalid access taken

### ISSUE THREAD

**Issue by MostafaAbuZeid** [socioboard/Socioboard-Core-3.0#68]
In need  to know by what i fill down the below settings:
"FacebookAuthUrl":""

**Comment by alshaikh1** [comment]
use:
http://www.facebook.com/v2.0/dialog/oauth/?scope=user_friends,user_status,publish_actions,user_posts,email,publish_actions,manage_pages

**Comment by socioboard** [comment]
Hi MostafaAbuZeid,
hope you got your solution am closing this issue if any prob pls reopen this 
Thanks
SB Team
