### ISSUE TITLE
Error loading project files

### ISSUE THREAD

**Issue by EmmaSWDB** [socioboard/Socioboard-Core-3.0#69]
I downloaded the project here: [https://github.com/socioboard/Socioboard-Core-3.0)](url)
 When I open the project this window appears:
![errorsb2](https://user-images.githubusercontent.com/37591119/37669821-64bef2c4-2c2d-11e8-9649-17d7a72a2d51.png)
The in the solution explorer the files cannot be loaded: 
![errorsb](https://user-images.githubusercontent.com/37591119/37669834-69ad09ba-2c2d-11e8-8dfd-e4029c661ed8.png)
In using VS2015
![errorsb3](https://user-images.githubusercontent.com/37591119/37669907-94943a54-2c2d-11e8-8131-8d35e16219b5.png)
I have tried the instructions in this post: [https://github.com/socioboard/Socioboard-Core-3.0/issues/39](url) 
but it didn´t worked for me

**Comment by socioboard** [comment]
Hi Emma,
please download file from given path:
https://github.com/socioboard/Socioboard-Core-3.0.git
if you still facing problem please let us know.

Thanks  
SB Team

**Comment by socioboard** [comment]
Hi Emma,
I hope you have found solution for now am closing this issue .in future if you have any issue regarding this you can reopen it .

Thanks
SB Team
