### ISSUE TITLE
Socioboard project  insert issue

### ISSUE THREAD

**Issue by preetammishra72** [socioboard/Socioboard-Core-3.0#70]
Hi Sir,
I have downloaded project and configure it.
But While registering I am getting exception "No persister for: Domain.Socioboard.Models.User"
Please help how to resolve this issue.
Please find the screen sort for exception.
email-preetammishra72@gmail.com
![socioboardscreensort](https://user-images.githubusercontent.com/5119840/38170882-8736c902-35ac-11e8-9310-13e02cbd81d2.png)

Regards,
Preetam

**Comment by socioboard** [comment]
Hi preetammishra72,
have you given proper connection string value .if given please check inner error once .

Thanks
SB Team

**Comment by preetammishra72** [comment]
Ok.Thanks.I am looking.

**Comment by socioboard** [comment]
Hi preetammishra72,
Hope you have found solution for it ,for now am closing this issue .In future if same  problem occur reopen this bug .
 
Thanks
SB Team
