### ISSUE TITLE
Getting error after while sign up

### ISSUE THREAD

**Issue by shambhuadvanz101** [socioboard/Socioboard-Core-3.0#71]
Hi,
I have successfully install soundboard on my local with .net. All things are working well but when I am trying to  sign up than getting error "Cant create user".

Could you please have a look this ?

**Comment by socioboard** [comment]
Hi shambhuadvanz101,
check once connection string values.

**Comment by shambhuadvanz101** [comment]
Hello,

I have put correct mongodb login, what string are you talking me ?

Regard

**Comment by socioboard** [comment]
database connectionstring

**Comment by shambhuadvanz101** [comment]
I have correct database string . I can share my screen you would like to check.

**Comment by shambhuadvanz101** [comment]
Please check strings here
Mysql
 <property name="connection.connection_string">
      Data Source=localhost;User ID=root;Password=aspl101;persist security
info=False;initial catalog=socioboardlive;pooling=true;charset=utf8;
port=3306;
    </property>


Mongo here

"MongoDbConnectionString": "mongodb://sb:sb123@localhost",
    "MongoDbName": "socialboard",


Could you please access my computer via remote desktop for faster assist?

**Comment by socioboard** [comment]
ok sure before this check once inner error and give me screen shot
 what does it show?

**Comment by shambhuadvanz101** [comment]
Sure,

Please have a look in attachment.

**Comment by socioboard** [comment]
have found nothing here just post the pic here

**Comment by shambhuadvanz101** [comment]
Not getting you, Should I share my screen ?

**Comment by socioboard** [comment]
Hi  shambhuadvanz101 ,
okay , just co-ordinate with our support team they will assist you.

Thanks
SB Team

**Comment by shambhuadvanz101** [comment]
I appreciate your help. How much time it will take, Actually I need show
demo to client.

**Comment by socioboard** [comment]
Hi shambhuadvanz101 ,
Hope you have found the solution for now am closing this issue .
In future if any prob regarding project raise new ticket .

Thanks
SB Team
