### ISSUE TITLE
Facebook enforces HTTPS Authentication

### ISSUE THREAD

**Issue by obusher** [socioboard/Socioboard-Core-3.0#75]
Facebook only allows to redirect to https:// sites after using the OAuth Client Token Flow(2.12).
The default FacebookRedirectUrl in appsettings.json of Socioboard redirects to http://localhost:9821/FacebookManager/Facebook. Sign-up and Sign-in with Facebook is broken.

![https](https://user-images.githubusercontent.com/1913681/39965624-d1af1cda-569c-11e8-8889-7be227732ba7.png)

![https2](https://user-images.githubusercontent.com/1913681/39969032-7dacfa28-56d6-11e8-9e51-cd626a46cdfc.png)

**Comment by socioboard** [comment]
Hi obusher,
I hope you have found the solution,sorry for late reply .
Check with facebook developer document to know more about it .

Thanks
SB Team
