### ISSUE TITLE
Sign-in with Email and Password does not work

### ISSUE THREAD

**Issue by obusher** [socioboard/Socioboard-Core-3.0#76]
Sign-in with Email and Password results in output of an error:
"It seems like your connectivity to the internet is impaired"
(Ubuntu 18.04, Firefox 60.0.1 (64-bit))

![signin](https://user-images.githubusercontent.com/1913681/40906646-b64add3e-67e1-11e8-8efd-5e2343ebfaa6.png)

**Comment by socioboard** [comment]
Hi obusher,
We have not test with ubantu, let our team to test with this and let you know when updated.
thanks for informing about this issue.

**Comment by socioboard** [comment]
Hi obusher,
I hope you have found the solution for now am closing this issue .

Thanks
SB Team

**Comment by obusher** [comment]
Problem still exist.
I do not have any network issues, otherwise i would not open a issue...
This issue does not exist if you use firefox in a private instance. (Private Window)
