### ISSUE TITLE
Sign-in with Facebook does not work

### ISSUE THREAD

**Issue by obusher** [socioboard/Socioboard-Core-3.0#77]
Sign-in with Facebook returns a blank white site in the browser with following link:
(Ubuntu 18.04, Firefox 60.0.1 (64-bit))

https://www.socioboard.com/FacebookManager/Facebook?code=AQBvGAQqR1czSlkKZNCgMceobVa8-rpZS-mNgFTmI8xUyEC0ka8c2IxoVAzaWt7c-iAr8W73-iHFXrZrLDdFt03LEvY0M8RUPRI-qdnuvGW0h1a38Dm5SciQZ0M4em2J3Qxml-mg34l0DYjWNGpUNDqwYh33nNnoBNfNLte8njUf0QO16hH_EWuZtxTtpyD7Bxh5_VnbANR4CybwPpNJURHJz2Qx--15u9k1l6cxU_hMVdnWcTVlwYHo2yxeARfh7fFRWRWhDCowQMlPFNobW-tu150eCxgf6THjeJgEnAqUpQ4mt60iz2SX989B-DvQbaJelrYYA-ecYh8QZk7Hr4Mn#_=_

Screenshot:
![screenshot from 2018-06-04 10-07-01](https://user-images.githubusercontent.com/1913681/40905895-8ea6bd18-67df-11e8-800c-cb78cbb22ee8.png)

**Comment by socioboard** [comment]
Hi obusher,
can you check it with facebook developer document ,what it require please go through it once

Thanks
