### ISSUE TITLE
Cant create user

### ISSUE THREAD

**Issue by khususgw** [socioboard/Socioboard-Core-3.0#8]
i have done build using visual studio 2015 in my windows server 2008 and mariadb

but when i try to create new user 
a red pop up (cant create user) is showing 

but when i try to connect my database using phpmyadmin and heidisql my database is connected, 

any one can help me to solve my problem? thanks

**Comment by socioboard** [comment]
Unable to save the data in database check your db connection string setting properly.

Thanks
Socioboard Team

**Comment by khususgw** [comment]
i have check the connection, its localhost connected to mariaDB using username + password i create in mariadb, i can access it using phpmyadmin from iis 
, i have change the database name to socioboardlive, and create new query but same result its cant connected from localhost:9821

**Comment by socioboard** [comment]
Hi Khususgw,
Take new upadates of socioboard 3.0 and check it.
if you face any issue let us know.

Thanks
Socioboard Team

**Comment by khususgw** [comment]
okaay, i will try new update, and i will ask again if any error, thanks

**Comment by khususgw** [comment]
after download new updates, i still get same error, cant create user, im using vs 2015, mariadb, iis, 
db name same as hibernate.cfg,

**Comment by socioboard** [comment]
Hi
khususgw ,
can you give provide your teamviewer or skype id
for remote access.
