### ISSUE TITLE
how we can align update source for Socioboard-Core-3.0?

### ISSUE THREAD

**Issue by maksudcs** [socioboard/Socioboard-Core-3.0#9]
Hello Socioboard Team,

I am regularly working in Socioboard-Core-3.0, fixing error. Alongside socioboard team release their source. 

**1. So, how we can align new release source of Socioboard-Core-3.0?
2. Can we commit our source to GitHub**

**Comment by socioboard** [comment]
Hey Maksudcs,

I will give you access to the repo, you can commit your codes to the master repo.
